### ISSUE TITLE
No Issues

### ISSUE THREAD

**Issue by ta-riq** [ThemeZee/mercia#1]

**Comment by ta-riq** [comment]
Sorry. for this bad way of contacting you.  I am very much unable to contact with you other way.

**Comment by Netzberufler** [comment]
Hi there,

Unable to contact me? 

I have a contact form and email address on my website, plus Twitter and Facebook profiles. You can reach me quickly on each one of these. 

Since this is not an issue related to the theme I'm closing this thread. You can simply write me an email :)

Cheers,
Thomas
